version: "3"

services:

  python-fastapi:
    build:
      context: python-fastapi
    ports:
      - 8000
    deploy:
      replicas: 2

  node-fastify:
    build:
      context: node-fastify
    ports:
      - 8010
    deploy:
      replicas: 2

  aspnet-core:
    build:
      context: aspnet-core
    ports:
      - 8020
    deploy:
      replicas: 2

  nginx-reverse-proxy:
    image: nginx:alpine
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python-fastapi
