version: "3"

services:

  python-fastapi:
    build:
      context: python-fastapi
    ports:
      - 8000

  nginx-reverse-proxy:
    image: nginx:alpine
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python-fastapi
