version: "3"

x-healthcheck:
  &default-healthcheck
  interval: 10s
  timeout: 5s
  retries: 1
  start_period: 5s

services:

  python-fastapi:
    build:
      context: python-fastapi
    ports:
      - 8000
    deploy:
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: wget -qO- http://0.0.0.0:8000 || exit 1

  node-fastify:
    build:
      context: node-fastify
    ports:
      - 8010
    deploy:
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: wget -qO- http://0.0.0.0:8010 || exit 1

  aspnet-core:
    build:
      context: aspnet-core
    ports:
      - 8020
    deploy:
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: wget -qO- http://0.0.0.0:8020 || exit 1

  nginx-reverse-proxy:
    image: nginx:alpine
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      python-fastapi:
        condition: service_healthy
      node-fastify:
        condition: service_healthy
      aspnet-core:
        condition: service_healthy
